using System.Diagnostics;
using System.IO.Compression;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MechanicaLauncher.Core.Game;

public sealed class NeoForgeInstaller
{
    private static readonly HttpClient Http = new();
    private const string MavenBase = "https://maven.neoforged.net";
    private readonly string _sharedDir;
    private readonly string _instanceGameDir;

    public NeoForgeInstaller(string sharedDir, string instanceGameDir)
    {
        _sharedDir = sharedDir;
        _instanceGameDir = instanceGameDir;
    }

    public event Action<string, double>? ProgressChanged;

    public async Task<List<string>> GetVersionsAsync(string mcVersion)
    {
        var url = $"{MavenBase}/api/maven/versions/releases/net/neoforged/neoforge";
        var response = await Http.GetFromJsonAsync<NeoForgeVersionList>(url);
        if (response?.Versions == null) return [];

        var mcMinor = mcVersion.StartsWith("1.") ? mcVersion[2..] : mcVersion;

        return response.Versions
            .Where(v => v.StartsWith(mcMinor + ".") || v.StartsWith(mcMinor + "-"))
            .Reverse()
            .Take(20)
            .ToList();
    }

    public async Task InstallAsync(string mcVersion, string neoVersion)
    {
        ProgressChanged?.Invoke("Downloading NeoForge installer...", 10);

        var installerUrl = $"{MavenBase}/releases/net/neoforged/neoforge/{neoVersion}/neoforge-{neoVersion}-installer.jar";
        var tmpPath = Path.Combine(Path.GetTempPath(), $"neoforge-{neoVersion}-installer.jar");
        var bytes = await Http.GetByteArrayAsync(installerUrl);
        await File.WriteAllBytesAsync(tmpPath, bytes);

        var versionId = $"neoforge-{neoVersion}";
        var instanceVersionDir = Path.Combine(_instanceGameDir, "versions", versionId);
        Directory.CreateDirectory(instanceVersionDir);

        // Extract version.json. Don't merge install_profile.json libs — the patched client, slim and
        // extra artifacts are located by fancymodloader's ProductionClientProvider via the
        // libraryDirectory system property, not the classpath. Adding them as regular libraries makes
        // the JVM auto-load duplicate modules that collide with the provider-built minecraft module.
        using (var zip = ZipFile.OpenRead(tmpPath))
        {
            var versionEntry = zip.GetEntry("version.json")
                ?? throw new InvalidDataException("version.json not found in NeoForge installer");
            using var stream = versionEntry.Open();
            using var reader = new StreamReader(stream);
            await File.WriteAllTextAsync(Path.Combine(instanceVersionDir, $"{versionId}.json"), await reader.ReadToEndAsync());
        }

        // NeoForge 1.20.5+ ships a client.jar that must be generated by the installer's processors
        // (patching + remapping vanilla). Running the installer headless is the supported way.
        Directory.CreateDirectory(_sharedDir);
        var profilesPath = Path.Combine(_sharedDir, "launcher_profiles.json");
        if (!File.Exists(profilesPath))
            await File.WriteAllTextAsync(profilesPath, "{\"profiles\":{}}");

        var javaPath = JavaFinder.FindAllJava()
            .Where(j => j.MajorVersion >= 17)
            .OrderByDescending(j => j.MajorVersion)
            .Select(j => j.Path)
            .FirstOrDefault() ?? throw new Exception("Java 17+ not found. Install Java 21 first.");

        // Use java.exe (console) instead of javaw.exe so we can capture installer stdout/stderr.
        var javaExe = javaPath.EndsWith("javaw.exe", StringComparison.OrdinalIgnoreCase)
            ? javaPath[..^5] + ".exe"
            : javaPath;
        if (!File.Exists(javaExe)) javaExe = javaPath;

        ProgressChanged?.Invoke("Running NeoForge installer (patching client)...", 40);

        var psi = new ProcessStartInfo
        {
            FileName = javaExe,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
        };
        psi.ArgumentList.Add("-jar");
        psi.ArgumentList.Add(tmpPath);
        psi.ArgumentList.Add("--installClient");
        psi.ArgumentList.Add(_sharedDir);

        using var proc = Process.Start(psi) ?? throw new Exception("Failed to start NeoForge installer");

        var stdoutLines = new List<string>();
        proc.OutputDataReceived += (_, a) =>
        {
            if (a.Data == null) return;
            stdoutLines.Add(a.Data);
            if (a.Data.StartsWith("Processor:", StringComparison.OrdinalIgnoreCase))
                ProgressChanged?.Invoke($"NeoForge: {a.Data[..Math.Min(80, a.Data.Length)]}", 60);
        };
        var stderrBuf = new List<string>();
        proc.ErrorDataReceived += (_, a) => { if (a.Data != null) stderrBuf.Add(a.Data); };
        proc.BeginOutputReadLine();
        proc.BeginErrorReadLine();
        await proc.WaitForExitAsync();

        try { File.Delete(tmpPath); } catch { }

        var clientJar = Path.Combine(_sharedDir, "libraries", "net", "neoforged", "neoforge", neoVersion,
            $"neoforge-{neoVersion}-client.jar");

        if (proc.ExitCode != 0 || !File.Exists(clientJar))
        {
            var tail = string.Join("\n", stderrBuf.Concat(stdoutLines).TakeLast(30));
            throw new Exception(
                $"NeoForge installer exit {proc.ExitCode}, client.jar {(File.Exists(clientJar) ? "ok" : "MISSING")}:\n{tail}");
        }

        ProgressChanged?.Invoke("NeoForge installed!", 100);
    }

}

file sealed class NeoForgeVersionList
{
    [JsonPropertyName("versions")]
    public List<string>? Versions { get; set; }
}
